### ISSUE TITLE
Make it publishable

### ISSUE THREAD

**Issue by daviddias** [goga-m/js-ipfs-browser-performance#2]
@goga-m could you take from the Makefile on https://github.com/ipfs/website the targets `make deploy` and `make publish-to-domain` so that publishing to IPFS is made simpler?

**Comment by goga-m** [comment]
@diasdavid  sure,  I added the Makefile in the latest commit (https://github.com/ipfs/benchmark.js.ipfs.io/commit/f927f1595b374686ab31ca82d063f1410e827e84), containing the targets, tested locally and seems ok. Let me know if it works for you

Thanks

**Comment by daviddias** [comment]
It will be live soon: 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/1211152/33267000-a62ee56e-d36f-11e7-9f80-1dd243c90176.png">

Also, as a note, we had to rename because:

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1211152/33267016-b7a4f892-d36f-11e7-85a7-5a7e8fad7e1c.png">

Thanks @VictorBjelkholm :)

**Comment by goga-m** [comment]
@diasdavid @VictorBjelkholm thats great!

Thanks guys
